name: Interactive Rating

on:
  push:
    branches:
      - master # Change this to the branch you want to trigger the deployment from

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16 # Change this to your desired Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build the Vite.js application
        run: npm run build # Change this to your Vite.js build command

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: dist # Change this to the build output directory of your Vite.js application
          publish_branch: gh-pages # Change this if you want to deploy to a different branch
